apiVersion: v1
kind: Service
metadata:
  name: autoscaleapp-service
spec:
  type: NodePort
  selector:
    app: autoscaleapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
      nodePort: 30001

